'use strict';
//CAUTION this file is auto generated by index-handlers.js
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
var _react = _interopRequireDefault(require("react"));
Object.defineProperty(exports, "__esModule", {value: true});
exports.default = void 0;const Components={
	 'Join':	require('./../../node_modules/civil-server/dist/components/web-components/join'),
}
function WebComponents(props) {
  const objOrStr = props.webComponent;
  var WebComponentClass;
  var newProps = {};

  if (typeof objOrStr === 'object') {
    Object.assign(newProps, props, objOrStr);
    WebComponentClass = Components[objOrStr.webComponent];
  } else {
    // string
    Object.assign(newProps, props);
    WebComponentClass = Components[objOrStr];
  }

  if (typeof WebComponentClass === 'undefined') {
    logger.error('WebComponent not defined:', objOrStr);
    return null;
  }

  if (WebComponentClass.default) // commonJS module or require
    WebComponentClass = WebComponentClass.default;
  delete newProps.webComponent;
  return /*#__PURE__*/_react.default.createElement(WebComponentClass, newProps);
}
var _default = WebComponents;
exports.default = _default;

exports.WebComponents=WebComponents
exports.Components=Components

